services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DRIVE}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DRIVE}/radarr:/config
      - ${MEDIA_DRIVE}/Movies:/movies #optional
      - ${MEDIA_DRIVE}/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DRIVE}/sonarr:/config
      - ${MEDIA_DRIVE}/TV:/tv #optional
      - ${MEDIA_DRIVE}/Downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped