services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${DOCKER_DRIVE}/jellyfin:/config
      - ${MEDIA_DRIVE}:/media
    ports:
      - 8096:8096
    restart: unless-stopped