services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "papermc-server"
    environment:
      MEMORYSIZE: "8G"
      PAPERMC_FLAGS: ""
    volumes:
      - /home/sid/papermc:/data
    ports:
      - "25565:25565"
      - "9000:8123"
    stdin_open: true
    tty: true