services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
    volumes:
      - ${DOCKER_DRIVE}/plex:/config
      - ${MEDIA_DRIVE}:/media
    restart: unless-stopped