services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8112
      - TORRENTING_PORT=6881
    volumes:
      - ${DOCKER_DRIVE}/qbittorrent:/config
      - ${MEDIA_DRIVE}/Downloads:/downloads
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped