---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Tools:
  - Google Calendar:
      - abbr: CAL
        href: https://calendar.google.com
  - ChatGPT:
      - abbr: GPT
        href: https://chatgpt.com

- Social:
  - ProtonMail:
      - abbr: PM
        href: https://mail.proton.me/
  - Discord:
       - abbr: DC
         href: https://discord.com/app
  - Reddit:
       - abbr: RE
         href: https://reddit.com/

- Entertainment:
   - YouTube:
       - abbr: YT
         href: https://youtube.com/

- Developer:
   - Github:
       - abbr: GH
         href: https://github.com/


